<#
.SYNOPSIS
  Guided setup for AUX-027 peer API keys (OpenAI, Anthropic, Google/Gemini).

.DESCRIPTION
  Opens each provider's key page, prompts for the key, writes eval/.peer-keys.env
  (gitignored), and optionally stores the same values as GitHub Actions secrets
  on Auricrux/auricrux-app so CI can run the blind comparison.

.EXAMPLE
  .\scripts\setup-peer-keys.ps1
  .\scripts\setup-peer-keys.ps1 -SkipBrowser -GitHubSecrets
#>
[CmdletBinding()]
param(
    [switch]$SkipBrowser,
    [switch]$GitHubSecrets,
    [string]$Repo = "Auricrux/auricrux-app"
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$envFile = Join-Path $root "eval\.peer-keys.env"

Write-Host ""
Write-Host "AUX-027 peer keys setup" -ForegroundColor Cyan
Write-Host "These keys let Auricrux collect ChatGPT / Claude / Gemini answers for the"
Write-Host "blind construction quality comparison. Keys stay local (and optional GH secrets)."
Write-Host ""

$providers = @(
    @{
        Name = "OpenAI (ChatGPT)"
        Env  = "OPENAI_API_KEY"
        Url  = "https://platform.openai.com/api-keys"
        Tip  = "Create an API key. Billing must be enabled for gpt-4o calls."
        Gh   = "PEER_OPENAI_API_KEY"
    },
    @{
        Name = "Anthropic (Claude)"
        Env  = "ANTHROPIC_API_KEY"
        Url  = "https://console.anthropic.com/settings/keys"
        Tip  = "Create an API key. Needs console credits for Sonnet."
        Gh   = "PEER_ANTHROPIC_API_KEY"
    },
    @{
        Name = "Google AI Studio (Gemini)"
        Env  = "GOOGLE_API_KEY"
        Url  = "https://aistudio.google.com/apikey"
        Tip  = "Easiest free tier. Create an API key in AI Studio."
        Gh   = "PEER_GOOGLE_API_KEY"
    }
)

$existing = @{}
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$' -and $Matches[1] -notmatch '^#') {
            $existing[$Matches[1]] = $Matches[2]
        }
    }
    Write-Host "Found existing $envFile (values can be replaced)." -ForegroundColor DarkGray
}

$values = @{}
foreach ($p in $providers) {
    Write-Host ""
    Write-Host "=== $($p.Name) ===" -ForegroundColor Yellow
    Write-Host $p.Tip
    Write-Host "Page: $($p.Url)"
    if (-not $SkipBrowser) {
        try { Start-Process $p.Url } catch { }
        Start-Sleep -Milliseconds 400
    }

    $have = $existing[$p.Env]
    if ($have) {
        $masked = if ($have.Length -gt 8) { $have.Substring(0, 4) + "…" + $have.Substring($have.Length - 4) } else { "****" }
        Write-Host "Current: $masked"
        $keep = Read-Host "Keep existing key? [Y/n]"
        if ([string]::IsNullOrWhiteSpace($keep) -or $keep -match '^[Yy]') {
            $values[$p.Env] = $have
            continue
        }
    }

    $secure = Read-Host "Paste API key (input hidden)" -AsSecureString
    $bstr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
        $plain = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($bstr)
    } finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($bstr)
    }
    if ([string]::IsNullOrWhiteSpace($plain)) {
        Write-Host "Skipped $($p.Name) — leave blank to collect only available peers." -ForegroundColor DarkYellow
        continue
    }
    $values[$p.Env] = $plain.Trim()
}

$lines = @(
    "# Generated by scripts/setup-peer-keys.ps1 — DO NOT COMMIT",
    "# $(Get-Date -Format o)"
)
foreach ($p in $providers) {
    $v = $values[$p.Env]
    if ($v) { $lines += "$($p.Env)=$v" }
}
$lines | Set-Content -Path $envFile -Encoding utf8
Write-Host ""
Write-Host "Wrote $envFile" -ForegroundColor Green

if ($GitHubSecrets -or (Read-Host "Also store as GitHub secrets on $Repo? [y/N]") -match '^[Yy]') {
    foreach ($p in $providers) {
        $v = $values[$p.Env]
        if (-not $v) { continue }
        $v | gh secret set $p.Gh --repo $Repo
        Write-Host "Set secret $($p.Gh)" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "Next:" -ForegroundColor Cyan
Write-Host "  .\scripts\run-peer-comparison.ps1"
Write-Host "  (collects Auricrux + any peers with keys, auto-scores, writes eval/reports/)"
Write-Host ""
